---
deployment:
  tasks:
    - export REPODIR=/home/skyesola/phplogin/
    - export REPOPATH=/home/skyesola/phplogin/.git
    - export DEPLOYPATH=/home/skyesola/bloodbankfinder.com/phplogin
    - rsync -r --times --exclude '.git' --exclude '.cpanel.yml' $REPODIR $DEPLOYPATH #copy all from root
    - cd $DEPLOYPATH
    - export changedFiles="$(git --git-dir=$REPOPATH --no-pager diff-tree -r --name-only --no-commit-id HEAD)"
    - php composer.phar install
    - echo "Run the npm"
    - /usr/local/bin/npm install
